meta_product_name: "Intranet - CFDT services"
meta_title: "Intranet - CFDT services"
meta_description: "Intranet de la CFDT Services, pour le partage des informations au fonctionnement interne de la CFDT Services."
meta_image: "cover.png" # existe dans `app/assets/images/`
