toolbar:
  - styleselect | bold italic | undo redo
  - image | link
plugins:
  - image
  - link
default: &default
  plugins:
    - image
    - link

alternate:
  <<: *default
  toolbar: styleselect | bold italic | undo redo | table
  plugins:
    - table
